---
  - hosts: control-plane
    become: yes

    tasks:
      - name: Download and extract remote istio archive
        ansible.builtin.unarchive:
          src: https://github.com/istio/istio/releases/download/1.14.0/istio-1.14.0-linux-amd64.tar.gz
          dest: ~/
          remote_src: yes
        tags:
          - download

      - name: Copy istioctl to /etc/bin
        ansible.builtin.copy:
          src: ~/istio-1.14.0/bin/istioctl
          dest: /usr/bin/istioctl
          mode: '0755'
        tags:
          - copy

      - name: Install istio
        ansible.builtin.shell:
          cmd: KUBECONFIG=/etc/kubernetes/admin.conf istioctl install --set profile=default -y
        tags:
          - install
